export const t = {
  fr: {
    tabs: { all: 'Tous', articles: 'Articles', journals: 'Journaux', academies: 'Académies', institutions: 'Institutions', blogs: 'Blogs' },
    search: 'Rechercher une organisation...',
    submit: 'Soumettre une ressource',
    hero: { title: 'Explorez la recherche en santé en afrique', 
        subtitle: '  La plateforme de référence pour accéder aux journaux, académies et institutions de recherche en santé à travers l\'Afrique',
        about: 'À propos de cette ressource',
        website: 'Accès au site web',
        loadingdata:"Données encours de chargement...",
        statut:"Statut",
        explore:"Visiter",
        all:"Tous",
        resourcenotfound:"Ressource non trouvée",
        back:"Retour",
        close:"Fermer",
        name:"Nom/titre",
        description: "Description",
        selectedfile: "Fichier sélectionné: ",
        filedescription: "Sélectionnez une image (max 5MB) ou laissez vide pour l'image par défaut",
        uploading: "Upload en cours... ",
        cancel: "Annuler",
        sending: "Envoi...",
        submit: "Soumettre",
        uploadProgress: "Progression de l'upload: ",
        isbnnumber: "Numéro ISBN",
        statutdetails: "Description du statut",
        french: "Français",
        english:"Anglais",
        publishthe: "Publié le",
        language: "Langue" },
    filters: { type: 'Type de ressource', 
        country: 'Pays', clear: 'Effacer les filtres' , academy: 'Académie'},
    loading: 'Données encours de chargement...'
  },
  en: {
    tabs: { all: 'All', articles: 'Articles', journals: 'Journals', academies: 'Academies', institutions: 'Institutions', blogs: 'Blogs' },
    search: 'Search for an organization...',
    submit: 'Submit a resource',
    hero: { title: 'Explore the best African health resources',
         subtitle: 'Articles, journals, academies, institutions and blogs selected for you.',
        about: 'About this resource',
        website: 'Access the website',
        statut:"Status"  ,
        explore:"Explore" ,
        close:"Close" ,
        name:"Name/Title",
        description: "Description",
        selectedfile: "Selected file: ",
        filedescription: "Select an image (max 5MB) or leave empty for default image",
        uploading: "Uploading... ",
        cancel: "Cancel",
        sending: "Sending...",
        submit: "Submit",
        uploadProgress: "Upload progress: ",
        isbnnumber: "ISBN number",
        statutdetails: "Status description",
        french: "French",
        english:"English", 
        publishthe: "Published on", 
        language: "Language" ,
        all: "All",
        resourcenotfound: "Resource not found",
        back: "Back",
         },
    filters: { type: 'Resource type', country: 'Country', clear: 'Clear filters', academy: 'Academy' },
    loading: 'Data loading...'
  }
};
